### ISSUE TITLE
Remove items T005 and T006

### ISSUE THREAD

**Issue by bozorgzadeh** [qualiticcommunity/qualiticcommunity.github.io#49]
Items T005 and T006 are about the incremental test coverage. 
Most teams have disabled these items. So I recommend to just remove them.
These are the reasons that I think these items are candidates to be removed: 

1. Some CLs are just about data models (simple data objects with setters or getrers), Protobuf objects, or simple logic that does not require a test. The incremental test coverage complains for these CLs but we do not like it.
2. Someone may argue that these items are useful when a team works on a legacy code and it wants to introduce the tests incrementally. But we have already handled the incremental introduction of tests by putting several items for global coverage with different percentage values as the expected threshold.  (By putting higher values in higher maturity levels)
3. When we want to enhance our test coverage, the global view leads us better. We can find the scopes with the higher potential risk and the higher reported bugs and prioritize them over the low risk regions of code.

**Comment by emranbm** [comment]
I agree that most teams at Sahab have intentionally ignored this item, and hence it's a good idea to remove them at all.

**Comment by MSDehghan** [comment]
We have disabled this item too so I'm ok to remove this item. Thank you @bozorgzadeh  for this issue.
